### ISSUE TITLE
cannot open iris model

### ISSUE THREAD

**Issue by sandesh1994199** [Rassibassi/mediapipeDemos#2]
(env_iris) c:\Users\snagaraj\Documents\git_repos\git_iris1>python iris.py -i gA_1_s1_2019-03-08T09;31;15+01;00_rgb_face.mp4
2021-09-01 14:37:21.813652: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "iris.py", line 167, in <module>
    main(args.i)
  File "iris.py", line 69, in main
    ) = from_landmarks_to_depth(
  File "c:\Users\snagaraj\Documents\git_repos\git_iris1\custom\iris_lm_depth.py", line 27, in from_landmarks_to_depth
    eye_contours, iris_landmarks = detect_iris(
  File "c:\Users\snagaraj\Documents\git_repos\git_iris1\custom\iris_lm_depth.py", line 61, in detect_iris
    outputs = tflite_inference(eye_frame_low / 127.5 - 1.0, model_path)
  File "c:\Users\snagaraj\Documents\git_repos\git_iris1\custom\core.py", line 11, in tflite_inference
    interpreter = tf.lite.Interpreter(model_path=model_path)
  File "C:\Users\snagaraj\documents\git_repos\git_iris1\env_iris\lib\site-packages\tensorflow\lite\python\interpreter.py", line 348, in __init__
    _interpreter_wrapper.CreateWrapperFromFile(
ValueError: Could not open 'models/iris_landmark.tflite'

**Comment by Rassibassi** [comment]
Seems like you did not download the `iris_landmark.tflite` file as described in the readme :)
